name: tests

on: ['push', 'pull_request']

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.2', '8.3', '8.4']
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-values: zend.assertions=1, assert.exception=1

      - name: Install Dependencies
        run: composer u --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Perform Tests
        run: composer test:unit